version: 2.1
commands:
    get:
        description: |
            This command echos "ip address" a curl query.
        steps:
            - run:
                command: curl icanhazip.com
                name: Getting My IP
    echo:
        description: |
            This command echos something in parameter.
        parameters:
            something:
                type: string
                default: CIRCLECI OR SQUARECI
        steps:
            - run:
                command: echo <<parameters.something>>
                name: Echo something in parameter
executors:
    default:
        description: |
            This is a sample executor using Docker and Node.
        docker:
            - image: cimg/base:stable
jobs:
    hello:
        description: |
            Hello, give me the IP address using this job through the step an command
        executor: default
        steps:
            - get
            - echo:
                something: TRIANGLE
